export const client = {
  name: "Premier Landscaping",
  tagline: "Professional landscaping services in Irvine",
  phone: "(949) 123-4567",
  email: "john@premier.com",
  address: "123 Main St",
  city: "Irvine",
  state: "CA",
  serviceArea: ["Irvine"],
  primaryColor: "#8b2500",
  industry: "landscaping",
  services: ["Lawn care","Garden design","Irrigation","Tree trimming","Mulching","Sod installation","Leaf removal"],
  cmsUrl: "https://cms.sebvia.com",
  tenantSlug: "premier-landscaping",
  googleAnalyticsId: '',
  domain: "premier.sebvia.com",
};
